AWSTemplateFormatVersion: 2010-09-09
Description: Test 1

Parameters:
  S3BucketName:
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: !Join [ "-", [ !Ref S3BucketName, !Sub '${AWS::AccountId}' ] ]